spring:
  application:
    name: delivery-system

  datasource:
    url: jdbc:postgresql://localhost:5433/delivery_db
    username: zachary
    password: zachary
    driver-class-name: org.postgresql.Driver
  web:
    error:
      include-message: always

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-minutes: 120
routing:
  osrm:
    base-url: http://router.project-osrm.org
