package com.zachary.delivery_system.enums;

public enum AuditAction {

    DELIVERY_CREATED,
    DELIVERY_UPDATED,
    DELIVERY_DRIVER_ASSIGNED,
    DELIVERY_ACCEPTED,
    DELIVERY_PICKED_UP,
    DELIVERY_STARTED,
    DELIVERY_DELIVERED,
    DELIVERY_FAILED,
    DELIVERY_RETRY_REQUESTED,
    DELIVERY_TRANSIT_RESUMED,
    DELIVERY_CUSTOMER_CONFIRMED,
    DELIVERY_CANCELLED,
    DELIVERY_RETURNED,

    DRIVER_CREATED,
    DRIVER_ACTIVATED,
    DRIVER_DEACTIVATED
}
